### ISSUE TITLE
Spectral mixing

### ISSUE THREAD

**Issue by rvanwijnen** [seguso/KritaColorPlus#2]
Hi seguso, I saw you are using the spectral mixing created by urzeye.
Please don't use it, it's using wrong data and wrong mixing algorithm.

I'm working on a version that is right.

I'm the author of Spectral.js which is the original software urzeye based his version on.

If you want to reach out you can contact me on Twitter @OneDayOfCrypto

**Comment by seguso** [comment]
Hi, do you want me to remove the code from this repo? Or can I just replace it with your new code, once it comes out? It's a pity to remove it, it works so well :). Well,  Let me know

**Comment by rvanwijnen** [comment]
That's up to you, I just wanted to let you know it's not right.
As I'm a new user on the krita forum I've reached my post limit and have to wait to post again.

I will be able to post on that forum again in a few hours.
If you read the forum posts you can see I'm pointing out to urzeye what is wrong with his code but he keeps working with it

I will try to implement the code myself in Krita but that will take some time as I'm not familiar with the Krita code base.

**Comment by seguso** [comment]
Ok, then, if it's ok for you I will just replace it with the new code as it comes out. :)
Thanks for the great work :)

**Comment by seguso** [comment]
replaced ! :))

**Comment by rvanwijnen** [comment]
If you could include the license found in https://github.com/rvanwijnen/spectral.js/blob/main/python/spectral.py
Then it's ok, awesome work implementing it!

**Comment by seguso** [comment]
I added the license on top of your code. I didn't move the code to a different file, I hope it's ok.

**Comment by rvanwijnen** [comment]
That’s fine!
You can close the issue if you like

**Comment by seguso** [comment]
ok ;)
